<?php

namespace Xgbnl\Fleet\Facades;

use Illuminate\Support\Facades\Facade;

class FleetFacade extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'fleet'; // TODO: Change the autogenerated stub
    }
}
